### PR TITLE
Doesn't build on GHC < 7.6

### PR DESCRIPTION
**Pull request by bergmark**
```
Data/IP/RouteTable/Internal.hs:261:12:
    Not in scope: foldl'
    Perhaps you meant one of these:
      `foldl1' (imported from Data.Foldable),
      `foldl1' (imported from Prelude),
      `foldl' (imported from Data.Foldable)
```

### CODE REVIEW

**Comment by bergmark** [comment]
I revised 1.4.0 on hackage, https://hackage.haskell.org/package/iproute-1.4.0/revisions/

**Comment by kazu-yamamoto** [comment]
My policy is to support the latest three versions. So, currently 7.6, 7.8 and 7.10 are supported. If users strongly want to use 7.4, I will consider. Otherwise, I will merge this pull request.

Cc: @bitlli

**Comment by hvr** [comment]
@kazu-yamamoto if you don't want to support `base < 4.6` that's ok, but then please say so in the `.cabal ` file by setting a tighter lower bound on `base`

**Comment by kazu-yamamoto** [comment]
The same change is already done in the master. I'm sorry for not merging this pull request.
