### ISSUE TITLE
iproute-1.6.0 fails to compile with GHC 7.0, 7.2 and 7.4 

### ISSUE THREAD

**Issue by hvr** [kazu-yamamoto/iproute#26]
The `.cabal` file claims that `iproute-1.6.0` is compatible with base-4.[345], and yet the compilation fails:

```
Building iproute-1.6.0...
Preprocessing library iproute-1.6.0...
Building library...
creating dist/dist-sandbox-a3344949/build
[1 of 8] Compiling Data.IP.Addr     ( Data/IP/Addr.hs, dist/dist-sandbox-a3344949/build/Data/IP/Addr.o )
[2 of 8] Compiling Data.IP.Mask     ( Data/IP/Mask.hs, dist/dist-sandbox-a3344949/build/Data/IP/Mask.o )
[3 of 8] Compiling Data.IP.Range    ( Data/IP/Range.hs, dist/dist-sandbox-a3344949/build/Data/IP/Range.o )
[4 of 8] Compiling Data.IP.Op       ( Data/IP/Op.hs, dist/dist-sandbox-a3344949/build/Data/IP/Op.o )
[5 of 8] Compiling Data.IP.Internal ( Data/IP/Internal.hs, dist/dist-sandbox-a3344949/build/Data/IP/Internal.o )
[6 of 8] Compiling Data.IP.RouteTable.Internal ( Data/IP/RouteTable/Internal.hs, dist/dist-sandbox-a3344949/build/Data/IP/RouteTable/Internal.o )

Data/IP/RouteTable/Internal.hs:265:12:
    Not in scope: foldl'
    Perhaps you meant one of these:
      `foldl1' (imported from Data.Foldable),
      `foldl1' (imported from Prelude),
      `foldl' (imported from Data.Foldable)
xcabal: Error: some packages failed to install:
iproute-1.6.0 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by kazu-yamamoto** [comment]
Are you fine with 8015e15?

**Comment by hvr** [comment]
16e677f looks good to me (which btw is just the #20 pull-request did as well :-) )
